name: Make videos
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: videopuppet/build-video-github-action@v1
      with:
        source-path: hello-world/src/script.yml
        github-token: ${{ secrets.GITHUB_TOKEN }}
