name: Make videos
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: videopuppet/build-video-github-action@test3
      with:
        source-path: hello-world/src/script.yml
        github-token: ${{ secrets.GITHUB_TOKEN }}
        api-url: https://ykrpzu47d4.execute-api.us-east-1.amazonaws.com/dev/video/build
