name: Make videos
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: videopuppet/build-video-github-action@v1.0.0
      id: video
      with:
        source-path: hello-world/script/source.yml
        github-token: ${{ secrets.GITHUB_TOKEN }}
        videopuppet-api-key: ${{ secrets.VIDEOPUPPET_API_KEY }}
        api-url: https://devapi.videopuppet.com/video/build
    - uses: actions/upload-artifact@v1
      with:
        name: video
        path: "${{ steps.video.outputs.video-file }}"
